"""Added performance_fee and Changed total_fee 

Revision ID: 5326c9604561
Revises: 9a3c5b980f19
Create Date: 2025-04-26 12:29:21.205573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5326c9604561'
down_revision: Union[str, None] = '9a3c5b980f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('performance_fee', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.00'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'performance_fee')
    # ### end Alembic commands ###
