"""Initial table creation

Revision ID: 9a3c5b980f19
Revises: 
Create Date: 2025-04-07 09:53:14.288350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3c5b980f19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('telephone_number', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('check_in', sa.DateTime(), nullable=False),
    sa.Column('check_out', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('type_of_entity', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('surname', sa.String(length=255), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=False),
    sa.Column('vat_id', sa.String(length=255), nullable=True),
    sa.Column('bank_account', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deactivation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('offeror_id', sa.Integer(), nullable=False),
    sa.Column('offeree_id', sa.Integer(), nullable=False),
    sa.Column('total_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('upon_signing', sa.Integer(), nullable=False),
    sa.Column('upon_completion', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=255), nullable=False),
    sa.Column('travel_expenses', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('accommodation_expenses', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('other_expenses', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['offeree_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['offeror_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('performance_type', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('social_media', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('stage_plan', sa.String(length=255), nullable=True),
    sa.Column('tech_rider', sa.String(length=255), nullable=True),
    sa.Column('photos', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('videos', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('audios', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('online_press', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('profile_offeror_id', sa.Integer(), nullable=False),
    sa.Column('profile_offeree_id', sa.Integer(), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('start', sa.Time(), nullable=False),
    sa.Column('end', sa.Time(), nullable=True),
    sa.Column('arrive', sa.DateTime(), nullable=False),
    sa.Column('stage_set', sa.Time(), nullable=False),
    sa.Column('stage_check', sa.Time(), nullable=False),
    sa.Column('catering_open', sa.Time(), nullable=True),
    sa.Column('catering_close', sa.Time(), nullable=True),
    sa.Column('meal_time', sa.Time(), nullable=True),
    sa.Column('meal_location_name', sa.String(length=255), nullable=True),
    sa.Column('meal_location_address', sa.String(length=255), nullable=True),
    sa.Column('accommodation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodation.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('profile')
    op.drop_table('contract')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('accommodation')
    # ### end Alembic commands ###
