"""Added performance_fee and Changed total_fee 

Revision ID: b6cb1771a18b
Revises: 9a3c5b980f19
Create Date: 2025-04-26 12:27:25.039741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6cb1771a18b'
down_revision: Union[str, None] = '9a3c5b980f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('performance_fee', sa.Numeric(precision=10, scale=2), nullable=False))
    op.alter_column('contract', 'total_fee', existing_type=sa.NUMERIC(precision=10, scale=2), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contract', 'total_fee', existing_type=sa.NUMERIC(precision=10, scale=2), nullable=False)
    op.drop_column('contract', 'performance_fee')
    # ### end Alembic commands ###
