"""Create all tables

Revision ID: 7f1f28ef17ec
Revises: 
Create Date: 2025-03-27 00:01:43.239637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f1f28ef17ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accommodation', 'contact_person',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('accommodation', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('accommodation', 'url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('event', 'contact_person',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('event', 'contact_phone',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'contact_phone',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('event', 'contact_person',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('accommodation', 'url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('accommodation', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('accommodation', 'contact_person',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
