"""ADDED deleted_at and desble_at in User and Contract tables

Revision ID: 9f01bbbafc91
Revises: 96ecf5a603bc
Create Date: 2025-03-27 11:47:26.308988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f01bbbafc91'
down_revision: Union[str, None] = '96ecf5a603bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('delete_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('disabled_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('delete_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'delete_at')
    op.drop_column('user', 'disabled_at')
    op.drop_column('contract', 'delete_at')
    # ### end Alembic commands ###
