"""CHANGE disable for is_active in USER table

Revision ID: ae651f025668
Revises: bb6f8f3ed857
Create Date: 2025-03-27 12:36:18.834406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae651f025668'
down_revision: Union[str, None] = 'bb6f8f3ed857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('user', 'disabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
