"""UPDATED deleted_at, desble_at, signed_at in User and Contract tables

Revision ID: bb6f8f3ed857
Revises: 9f01bbbafc91
Create Date: 2025-03-27 12:06:31.801672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb6f8f3ed857'
down_revision: Union[str, None] = '9f01bbbafc91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.add_column('contract', sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('contract', sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('contract', 'delete_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('user', 'disabled_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('user', 'delete_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'delete_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('user', 'disabled_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('contract', 'delete_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('contract', 'signed_at')
    op.drop_column('contract', 'disabled_at')
    op.drop_column('contract', 'disabled')
    # ### end Alembic commands ###
