"""added delete_date in User and Contract tables

Revision ID: bc0300ecc0e3
Revises: 1ceb9b7bcd9d
Create Date: 2025-04-04 15:23:46.039954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0300ecc0e3'
down_revision: Union[str, None] = '1ceb9b7bcd9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('delete_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('delete_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'delete_date')
    op.drop_column('contract', 'delete_date')
    # ### end Alembic commands ###
