"""CHANGE disabled_at for deactivation_date in USER table

Revision ID: dd39f48a2b5d
Revises: ae651f025668
Create Date: 2025-03-27 13:05:43.304963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd39f48a2b5d'
down_revision: Union[str, None] = 'ae651f025668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('deactivation_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('user', 'disabled_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('disabled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('user', 'deactivation_date')
    # ### end Alembic commands ###
